project_id = "bapqlyvfwxsichlyjxpd"

[api]
enabled = true
port = 54321

[db]
port = 54322

[functions.weather]
verify_jwt = false

[functions.crop-scan]
verify_jwt = true

[functions.field-analysis]
verify_jwt = true

[functions.fn-crop-disease]
verify_jwt = true

[functions.pesapal-ipn]
verify_jwt = false

[functions.pesapal-payment]
verify_jwt = false

[functions.verify-payment-status]
verify_jwt = false