
project_id = "bapqlyvfwxsichlyjxpd"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "https://cropgenius.lovable.dev"
additional_redirect_urls = [
  "http://localhost:3000/auth/callback",
  "http://localhost:54323/auth/callback",
  "https://cropgenius.lovable.dev/auth/callback",
  "https://cropgenius.netlify.app/auth/callback",
  "https://*.cropgenius.com/auth/callback"
]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_confirmations = false

[cors]
enabled = true
max_age = 86400 # 24 hours
allowed_origins = ["*"]
allowed_methods = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
allowed_headers = ["*"]

[realtime]
enabled = true

[edge_functions]
enabled = true

[functions.ai-chat]
verify_jwt = false

[functions.crop-scan]
verify_jwt = false

[functions.field-ai-insights]
verify_jwt = false

[functions.field-analysis]
verify_jwt = false

[functions.whatsapp-notification]
verify_jwt = false
import_map = [
  "https://deno.land/std@0.190.0/http/server.ts",
  "https://esm.sh/@supabase/supabase-js@2"
]

[functions.check-ai-insights]
verify_jwt = false
import_map = [
  "https://deno.land/std@0.190.0/http/server.ts",
  "https://esm.sh/@supabase/supabase-js@2"
]
