[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/pesapal/ipn"
  to = "/.netlify/functions/pesapal-ipn-public"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"