[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/pesapal/ipn"
  to = "/.netlify/functions/pesapal-ipn-public"
  status = 200

# SPA fallback for HTML requests only
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[functions]
  directory = "netlify/functions"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.png"
  [headers.values]
    Content-Type = "image/png"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"