name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      confirm_deploy:
        description: 'Confirm production deployment'
        required: true
        default: 'false'

jobs:
  prepare:
    name: Prepare Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Check deployment confirmation
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.confirm_deploy != 'true'
        run: |
          echo "Production deployment requires explicit confirmation"
          exit 1
          
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: coverage/
          
  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: npm run build:production
        env:
          VITE_MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
          VITE_SUPABASE_URL: ${{ secrets.PRODUCTION_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.PRODUCTION_SUPABASE_ANON_KEY }}
          
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/
          
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist/
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install deployment dependencies
        run: npm install -g firebase-tools
        
      - name: Deploy to Firebase Production
        run: firebase deploy --only hosting:production
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          
      - name: Create deployment tag
        run: |
          git tag production-$(date +%Y%m%d-%H%M%S)
          git push origin --tags
          
  monitor:
    name: Monitor Production Deployment
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run initial health check
        run: node scripts/production-health-check.js
        
      - name: Schedule monitoring
        run: |
          echo "::set-output name=monitoring_url::https://cropgenius-monitoring.vercel.app/api/trigger-monitoring?deployment_id=$(date +%Y%m%d-%H%M%S)"
          
      - name: Notify team
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { issue, repo } = context;
            github.rest.issues.createComment({
              owner: repo.owner,
              repo: repo.repo,
              issue_number: issue.number,
              body: `🚀 Production deployment completed!\n\nMonitoring dashboard: https://cropgenius-monitoring.vercel.app\n\nPlease verify the following:\n- [ ] Error rates are normal\n- [ ] API response times are acceptable\n- [ ] User flows are working correctly\n\nMonitoring will continue for the next 24 hours.`
            });